version: '3.4'

services:
  microserviceexample:
    image: ${DOCKER_REGISTRY-}microserviceexample
    build:
      context: .
      dockerfile: MicroserviceExample/Dockerfile
    environment:
      Couchbase__ConnectionString: "couchbase://cb"
      Couchbase__Username: "Administrator"
      Couchbase__Password: "password"
    ports:
    - "9090:80"
    depends_on:
    - cb
  cb:
    image: couchbase:enterprise-6.5.1
    ports:
    - "8091:8091"
